@base = http://localhost:3000/api/v1/payments

@tx_shift4 = e4c571a5-52ca-475c-baf1-113b2b9f0949
@tx_aci = ae5e13ec-5d82-40f5-91af-2613bdc9fade
POST  {{base}}/shift4
Content-Type: application/json

{
  "amount": "100000",
  "currency": "USD",
  "cardNumber": "4012000100000007", 
  "cvv": "123",
  "expMonth": "08",
  "expYear": "2024"
}

###

POST  {{base}}/aci
Content-Type: application/json

{
  "amount": "10002",
  "currency": "EUR",
  "cardNumber": "4012000100000007", 
  "cvv": "123",
  "expMonth": "08",
  "expYear": "2024"
}

###
GET {{base}}/{{tx_aci}}
