version: "3.8"
services:
  payment-service-app:
    build: .
    env_file:
      - .env
    ports:
      - "${EXPOSE_PORT}:${PORT}" # Mapping container port to host port
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT} # Ensure PORT is passed correctly
